### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by tessavdheiden** [martiniani-lab/pele#21]
Hey!

I've tried to install everything on my mac. It actually worked with the [previous](https://github.com/pele-python/pele) repo.

Here's the error:
`  File "/Users/tessavanderheiden/Documents/coding/pele/pele/potentials/__init__.py", line 60, in <module>
    from ._frozen_dof import FrozenPotentialWrapper
ModuleNotFoundError: No module named 'pele.potentials._frozen_dof'
`

So I think the setup_with_cmake step didn't work: `python setup_with_cmake.py build_ext -i --fcompiler=gfortran`

Any tips?

I also don't know how to do this:
_make sure to add the install directory to your PYTHONPATH environment variable._

Best,
Tessa

**Comment by spraharsh** [comment]
Thank you for reaching out! 

Can you also share the output of `python setup_with_cmake.py build_ext -i` in a text file just to make sure that your package is installed

To add the module to your PYTHONPATH, you have to do `export PYTHONPATH=/your/pele-location/pele/pele` before you run any code on the terminal. This may be different if you are running Python from other environments (because your Python needs to register the path), so can you also share what script you're running and how you're running it

**Comment by tessavdheiden** [comment]
Hey Praharsh,

Thanks for your comment and help. The txt file was sent!

I've also added the pele location to PYTHONPATH, but that didn't help, unfortunately. 
I've run `python examples/new_potential/mypotential.py` in Pycharm and in terminal, but pele cannot be found.

Best,
Tessa

**Comment by spraharsh** [comment]
Check whether #22 fixes the installation issues, since the txt file points to CVODE causing installation errors. to compile, use `python setup_with_cmake.py build_ext -i --with-cvode 0` . Also before recompiling run `rm -rf build cythonize.dat  CMakeCache.txt cmake_install.cmake` to remove cached compilation files

**Comment by tessavdheiden** [comment]
Hey Praharsh,

Many thanks for your help! I've pulled the latest code and ran:
- `python setup_with_cmake.py build_ext -i --with-cvode 0`
- `rm -rf build cythonize.dat  CMakeCache.txt cmake_install.cmake`

Unfortunately, I still get this error:
`ModuleNotFoundError: No module named 'pele.potentials._frozen_dof'` 

Even though my PYTHONPATH is:  /Users/tessavanderheiden/Documents/coding/pele/pele

Any ideas?

**Comment by spraharsh** [comment]
Fixed by #33
